spring:
  main:
    web-application-type: none
interval: 60000
opc-url: opc.tcp://10.65.162.130:4840
username: TRQ_CQKSJ
password: 57a98A209@77
push-url: http://localhost:6666/gas/add
push-multi-url: http://localhost:6666/gas/multi/add
region: daqing
points:
  list:
    - { point: QH1_FIQ6501_002F.PV, pname: 正向标况瞬时流量 ,unit: Nm3/h ,tableName: dq_QH1_FIQ6501_002F }
    - { point: QH1_FIQ6601_002F.PV, pname: 正向标况瞬时流量 ,unit: Nm3/h ,tableName: dq_QH1_FIQ6601_002F }
    - { point: QH1_FIQ6501_005F.PV, pname: 绝对压力 ,unit: Mpa ,tableName: dq_QH1_FIQ6601_005F }
    - { point: QH1_FIQ6601_005F.PV, pname: 绝对压力 ,unit: Mpa ,tableName: dq_QH1_FIQ6601_005F }
    - { point: QH1_FIQ6501_002B.PV, pname: 反向标况瞬时流量 ,unit: Nm3/h ,tableName: dq_QH1_FIQ6501_002B }
    - { point: QH1_FIQ6601_002B.PV, pname: 反向标况瞬时流量 ,unit: Nm3/h ,tableName: dq_QH1_FIQ6601_002B }
    - { point: QH1_FIQ6501_005F.PV, pname: 绝对压力 ,unit: Mpa ,tableName: dq_QH1_FIQ6501_005F }
    - { point: QH1_FIQ6601_005F.PV, pname: 绝对压力 ,unit: Mpa ,tableName: dq_QH1_FIQ6601_005F }
